# Site settings
title: The Bristol Politics Show
email: nicholasofwinchester@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Bristol Politics Show archive, current programme notes, stories,
  full shows, interviews, and listener information.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bristolpoliticsshow.github.io"
github_username: BristolPoliticsShow

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .bundle/
  - .github/
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - cloudflare-worker/
  - scripts/
  - vendor/
